### ISSUE TITLE
Suggestions?

### ISSUE THREAD

**Issue by NITPRUDO** [NITPRUDO/NIT-CMD#1]
Are there any suggestions for Beta 2?
Leave a comment if you do.
Note: This will close when Beta 2 is released.

**Comment by Wasserboy08** [comment]
1. Add EDIT (You may use the edit.com still found in 32bit windows)
2. See picture! (Unicode is █)
![image](https://cloud.githubusercontent.com/assets/22521667/23216457/50b91c46-f916-11e6-8420-84ee0a4d7484.png)
3. Fix DIR ( I didnt could try the v1f Beta so idk if its fixed yet)

**Comment by NITPRUDO** [comment]
1. I have a 64bit version of Windows. Can you send me the edit.com file?
2. That is a good idea. I dont know if there is a way i can keep it at the top of the window. I may just print it the first line.
3. DIR is still not fixed. If anyone has a suggestion on how to fix it, i will be happy to merge a PR.

**Comment by LunaSoftoffical** [comment]
I can send you edit.com from my XP laptop if you want it?

**Comment by NITPRUDO** [comment]
Sure, use discord to send it though.

**Comment by LunaSoftoffical** [comment]
I will DM you it

**Comment by Wasserboy08** [comment]
1. Add an type of mouse like used in mouse.com in DOS 6.22   (An block in which everything is inverted and which is the mouse)
2. Add both commands on that image below (filecreation and type)
![image](https://cloud.githubusercontent.com/assets/22521667/23219055/4f58ea86-f91e-11e6-9596-92bb92b8d40e.png)
3. Opening programs from nit-cmd
![image](https://cloud.githubusercontent.com/assets/22521667/23219124/7fbc1b12-f91e-11e6-9c86-dbdef864da4f.png)

**Comment by NITPRUDO** [comment]
Thanks for the suggestions, @Wasserboy08 . I will do some experimenting and some suggestions should be out tommorow.
